platform :ios, '10.0'
use_frameworks!

target 'BlueCap' do
  pod 'BlueCapKit', :path => '../..'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'BlueCapKit'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
                    else
                    config.build_settings['OTHER_SWIFT_FLAGS'] = ''
                end
            end
        end
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
   end
end
